name: deploy

on:                                                             # trigger
  workflow_call:                                                # when code needs to be called from another function

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Clone the code
      uses: actions/checkout@v7
    - name: Deploy the code via nginx
      run: cp index.html /var/www/html
    - name: Deploy the code.
      run: echo "Code deployed to AWS EC2 instance successfully"
