name: deploy

on:                                                             # trigger
  workflow_call:                                                # when code needs to be called from another function

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy the code
      run: echo "Code deployed to AWS EC2 instance successfully"
